/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as mainDashboardRouteRouteImport } from './routes/(main)/dashboard/route'
import { Route as mainDashboardIndexRouteImport } from './routes/(main)/dashboard/index'
import { Route as mainDashboardClientsRouteRouteImport } from './routes/(main)/dashboard/clients/route'
import { Route as mainDashboardInvoiceRouteRouteImport } from './routes/(main)/dashboard/invoice/route'
import { Route as mainDashboardSettingsRouteRouteImport } from './routes/(main)/dashboard/settings/route'
import { Route as mainDashboardClientsIndexRouteImport } from './routes/(main)/dashboard/clients/index'
import { Route as mainDashboardClientsNewRouteImport } from './routes/(main)/dashboard/clients/new'
import { Route as mainDashboardInvoiceIndexRouteImport } from './routes/(main)/dashboard/invoice/index'
import { Route as mainDashboardInvoiceIdRouteImport } from './routes/(main)/dashboard/invoice/$id'
import { Route as mainDashboardInvoiceNewRouteImport } from './routes/(main)/dashboard/invoice/new'
import { Route as mainDashboardClientsIdEditRouteImport } from './routes/(main)/dashboard/clients/$id/edit'
import { Route as mainDashboardInvoiceIdEditRouteImport } from './routes/(main)/dashboard/invoice/$id/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const mainDashboardRouteRoute = mainDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainDashboardIndexRoute = mainDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainDashboardRouteRoute,
} as any)
const mainDashboardClientsRouteRoute =
  mainDashboardClientsRouteRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => mainDashboardRouteRoute,
  } as any)
const mainDashboardInvoiceRouteRoute =
  mainDashboardInvoiceRouteRouteImport.update({
    id: '/invoice',
    path: '/invoice',
    getParentRoute: () => mainDashboardRouteRoute,
  } as any)
const mainDashboardSettingsRouteRoute =
  mainDashboardSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => mainDashboardRouteRoute,
  } as any)
const mainDashboardClientsIndexRoute =
  mainDashboardClientsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => mainDashboardClientsRouteRoute,
  } as any)
const mainDashboardClientsNewRoute = mainDashboardClientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => mainDashboardClientsRouteRoute,
} as any)
const mainDashboardInvoiceIndexRoute =
  mainDashboardInvoiceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => mainDashboardInvoiceRouteRoute,
  } as any)
const mainDashboardInvoiceIdRoute = mainDashboardInvoiceIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => mainDashboardInvoiceRouteRoute,
} as any)
const mainDashboardInvoiceNewRoute = mainDashboardInvoiceNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => mainDashboardInvoiceRouteRoute,
} as any)
const mainDashboardClientsIdEditRoute =
  mainDashboardClientsIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => mainDashboardClientsRouteRoute,
  } as any)
const mainDashboardInvoiceIdEditRoute =
  mainDashboardInvoiceIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => mainDashboardInvoiceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof mainDashboardRouteRouteWithChildren
  '/dashboard/clients': typeof mainDashboardClientsRouteRouteWithChildren
  '/dashboard/invoice': typeof mainDashboardInvoiceRouteRouteWithChildren
  '/dashboard/settings': typeof mainDashboardSettingsRouteRoute
  '/dashboard/': typeof mainDashboardIndexRoute
  '/dashboard/clients/new': typeof mainDashboardClientsNewRoute
  '/dashboard/invoice/$id': typeof mainDashboardInvoiceIdRouteWithChildren
  '/dashboard/invoice/new': typeof mainDashboardInvoiceNewRoute
  '/dashboard/clients/': typeof mainDashboardClientsIndexRoute
  '/dashboard/invoice/': typeof mainDashboardInvoiceIndexRoute
  '/dashboard/clients/$id/edit': typeof mainDashboardClientsIdEditRoute
  '/dashboard/invoice/$id/edit': typeof mainDashboardInvoiceIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/settings': typeof mainDashboardSettingsRouteRoute
  '/dashboard': typeof mainDashboardIndexRoute
  '/dashboard/clients/new': typeof mainDashboardClientsNewRoute
  '/dashboard/invoice/$id': typeof mainDashboardInvoiceIdRouteWithChildren
  '/dashboard/invoice/new': typeof mainDashboardInvoiceNewRoute
  '/dashboard/clients': typeof mainDashboardClientsIndexRoute
  '/dashboard/invoice': typeof mainDashboardInvoiceIndexRoute
  '/dashboard/clients/$id/edit': typeof mainDashboardClientsIdEditRoute
  '/dashboard/invoice/$id/edit': typeof mainDashboardInvoiceIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(main)': typeof mainRouteRouteWithChildren
  '/(main)/dashboard': typeof mainDashboardRouteRouteWithChildren
  '/(main)/dashboard/clients': typeof mainDashboardClientsRouteRouteWithChildren
  '/(main)/dashboard/invoice': typeof mainDashboardInvoiceRouteRouteWithChildren
  '/(main)/dashboard/settings': typeof mainDashboardSettingsRouteRoute
  '/(main)/dashboard/': typeof mainDashboardIndexRoute
  '/(main)/dashboard/clients/new': typeof mainDashboardClientsNewRoute
  '/(main)/dashboard/invoice/$id': typeof mainDashboardInvoiceIdRouteWithChildren
  '/(main)/dashboard/invoice/new': typeof mainDashboardInvoiceNewRoute
  '/(main)/dashboard/clients/': typeof mainDashboardClientsIndexRoute
  '/(main)/dashboard/invoice/': typeof mainDashboardInvoiceIndexRoute
  '/(main)/dashboard/clients/$id/edit': typeof mainDashboardClientsIdEditRoute
  '/(main)/dashboard/invoice/$id/edit': typeof mainDashboardInvoiceIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/clients'
    | '/dashboard/invoice'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/clients/new'
    | '/dashboard/invoice/$id'
    | '/dashboard/invoice/new'
    | '/dashboard/clients/'
    | '/dashboard/invoice/'
    | '/dashboard/clients/$id/edit'
    | '/dashboard/invoice/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/clients/new'
    | '/dashboard/invoice/$id'
    | '/dashboard/invoice/new'
    | '/dashboard/clients'
    | '/dashboard/invoice'
    | '/dashboard/clients/$id/edit'
    | '/dashboard/invoice/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/(main)'
    | '/(main)/dashboard'
    | '/(main)/dashboard/clients'
    | '/(main)/dashboard/invoice'
    | '/(main)/dashboard/settings'
    | '/(main)/dashboard/'
    | '/(main)/dashboard/clients/new'
    | '/(main)/dashboard/invoice/$id'
    | '/(main)/dashboard/invoice/new'
    | '/(main)/dashboard/clients/'
    | '/(main)/dashboard/invoice/'
    | '/(main)/dashboard/clients/$id/edit'
    | '/(main)/dashboard/invoice/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  mainRouteRoute: typeof mainRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/dashboard': {
      id: '/(main)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof mainDashboardRouteRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/dashboard/': {
      id: '/(main)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof mainDashboardIndexRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/clients': {
      id: '/(main)/dashboard/clients'
      path: '/clients'
      fullPath: '/dashboard/clients'
      preLoaderRoute: typeof mainDashboardClientsRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/invoice': {
      id: '/(main)/dashboard/invoice'
      path: '/invoice'
      fullPath: '/dashboard/invoice'
      preLoaderRoute: typeof mainDashboardInvoiceRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/settings': {
      id: '/(main)/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof mainDashboardSettingsRouteRouteImport
      parentRoute: typeof mainDashboardRouteRoute
    }
    '/(main)/dashboard/clients/': {
      id: '/(main)/dashboard/clients/'
      path: '/'
      fullPath: '/dashboard/clients/'
      preLoaderRoute: typeof mainDashboardClientsIndexRouteImport
      parentRoute: typeof mainDashboardClientsRouteRoute
    }
    '/(main)/dashboard/clients/new': {
      id: '/(main)/dashboard/clients/new'
      path: '/new'
      fullPath: '/dashboard/clients/new'
      preLoaderRoute: typeof mainDashboardClientsNewRouteImport
      parentRoute: typeof mainDashboardClientsRouteRoute
    }
    '/(main)/dashboard/invoice/': {
      id: '/(main)/dashboard/invoice/'
      path: '/'
      fullPath: '/dashboard/invoice/'
      preLoaderRoute: typeof mainDashboardInvoiceIndexRouteImport
      parentRoute: typeof mainDashboardInvoiceRouteRoute
    }
    '/(main)/dashboard/invoice/$id': {
      id: '/(main)/dashboard/invoice/$id'
      path: '/$id'
      fullPath: '/dashboard/invoice/$id'
      preLoaderRoute: typeof mainDashboardInvoiceIdRouteImport
      parentRoute: typeof mainDashboardInvoiceRouteRoute
    }
    '/(main)/dashboard/invoice/new': {
      id: '/(main)/dashboard/invoice/new'
      path: '/new'
      fullPath: '/dashboard/invoice/new'
      preLoaderRoute: typeof mainDashboardInvoiceNewRouteImport
      parentRoute: typeof mainDashboardInvoiceRouteRoute
    }
    '/(main)/dashboard/clients/$id/edit': {
      id: '/(main)/dashboard/clients/$id/edit'
      path: '/$id/edit'
      fullPath: '/dashboard/clients/$id/edit'
      preLoaderRoute: typeof mainDashboardClientsIdEditRouteImport
      parentRoute: typeof mainDashboardClientsRouteRoute
    }
    '/(main)/dashboard/invoice/$id/edit': {
      id: '/(main)/dashboard/invoice/$id/edit'
      path: '/edit'
      fullPath: '/dashboard/invoice/$id/edit'
      preLoaderRoute: typeof mainDashboardInvoiceIdEditRouteImport
      parentRoute: typeof mainDashboardInvoiceIdRoute
    }
  }
}

interface mainDashboardClientsRouteRouteChildren {
  mainDashboardClientsNewRoute: typeof mainDashboardClientsNewRoute
  mainDashboardClientsIndexRoute: typeof mainDashboardClientsIndexRoute
  mainDashboardClientsIdEditRoute: typeof mainDashboardClientsIdEditRoute
}

const mainDashboardClientsRouteRouteChildren: mainDashboardClientsRouteRouteChildren =
  {
    mainDashboardClientsNewRoute: mainDashboardClientsNewRoute,
    mainDashboardClientsIndexRoute: mainDashboardClientsIndexRoute,
    mainDashboardClientsIdEditRoute: mainDashboardClientsIdEditRoute,
  }

const mainDashboardClientsRouteRouteWithChildren =
  mainDashboardClientsRouteRoute._addFileChildren(
    mainDashboardClientsRouteRouteChildren,
  )

interface mainDashboardInvoiceIdRouteChildren {
  mainDashboardInvoiceIdEditRoute: typeof mainDashboardInvoiceIdEditRoute
}

const mainDashboardInvoiceIdRouteChildren: mainDashboardInvoiceIdRouteChildren =
  {
    mainDashboardInvoiceIdEditRoute: mainDashboardInvoiceIdEditRoute,
  }

const mainDashboardInvoiceIdRouteWithChildren =
  mainDashboardInvoiceIdRoute._addFileChildren(
    mainDashboardInvoiceIdRouteChildren,
  )

interface mainDashboardInvoiceRouteRouteChildren {
  mainDashboardInvoiceIdRoute: typeof mainDashboardInvoiceIdRouteWithChildren
  mainDashboardInvoiceNewRoute: typeof mainDashboardInvoiceNewRoute
  mainDashboardInvoiceIndexRoute: typeof mainDashboardInvoiceIndexRoute
}

const mainDashboardInvoiceRouteRouteChildren: mainDashboardInvoiceRouteRouteChildren =
  {
    mainDashboardInvoiceIdRoute: mainDashboardInvoiceIdRouteWithChildren,
    mainDashboardInvoiceNewRoute: mainDashboardInvoiceNewRoute,
    mainDashboardInvoiceIndexRoute: mainDashboardInvoiceIndexRoute,
  }

const mainDashboardInvoiceRouteRouteWithChildren =
  mainDashboardInvoiceRouteRoute._addFileChildren(
    mainDashboardInvoiceRouteRouteChildren,
  )

interface mainDashboardRouteRouteChildren {
  mainDashboardClientsRouteRoute: typeof mainDashboardClientsRouteRouteWithChildren
  mainDashboardInvoiceRouteRoute: typeof mainDashboardInvoiceRouteRouteWithChildren
  mainDashboardSettingsRouteRoute: typeof mainDashboardSettingsRouteRoute
  mainDashboardIndexRoute: typeof mainDashboardIndexRoute
}

const mainDashboardRouteRouteChildren: mainDashboardRouteRouteChildren = {
  mainDashboardClientsRouteRoute: mainDashboardClientsRouteRouteWithChildren,
  mainDashboardInvoiceRouteRoute: mainDashboardInvoiceRouteRouteWithChildren,
  mainDashboardSettingsRouteRoute: mainDashboardSettingsRouteRoute,
  mainDashboardIndexRoute: mainDashboardIndexRoute,
}

const mainDashboardRouteRouteWithChildren =
  mainDashboardRouteRoute._addFileChildren(mainDashboardRouteRouteChildren)

interface mainRouteRouteChildren {
  mainDashboardRouteRoute: typeof mainDashboardRouteRouteWithChildren
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainDashboardRouteRoute: mainDashboardRouteRouteWithChildren,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  mainRouteRoute: mainRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
